### ISSUE TITLE
Failed request does not return an error message

### ISSUE THREAD

**Issue by rs-simonbrahan** [workos/workos-php#108]
The following call returned a bad request at around 2022-08-15 10:17:47 UTC:

```
Client::request(
    Client::METHOD_POST,
    "sso/token",
    null,
    array (
        "client_id" => "client_01FSQHN26PD53TF3WJSG8YXEYZ",
        "client_secret" => hidden,
        "code" => hidden,
        "grant_type" => "authorization_code"
    )
)
```

However it also caused an undefined index error in this library:

```
PHP Error (8): 'Undefined index: message' from /var/www/api/v1/vendor/workos/workos-php/lib/Exception/BaseRequestException.php:33
```

This makes it difficult to see what the problem is with the request.

Ideally, the full response payload should be available from the exception.

**Comment by rs-simonbrahan** [comment]
Could I have an update on this?

**Comment by sheldonvaughn** [comment]
Hey @rs-simonbrahan - apologies for the delay - our team has been actively working on updating the SDKs in other areas. I can prioritize this in the coming 2 weeks (9/12-9/23). Please let me know if there is more urgency and I'm happy to try and engage other folks on the team!

**Comment by sheldonvaughn** [comment]
Hey @rs-simonbrahan just wanted to give you a quick update and let you know I'm working on a fix for this (as you were probably notified with the linked PR). Hoping to have it deployed today or early next week! Thanks for your patience while we resolve this issue.

**Comment by sheldonvaughn** [comment]
@rs-simonbrahan I just deployed v1.16.0 which should resolve this issue. Please keep us posted if we can help with anything further!
