### ISSUE TITLE
Severity: 8192 --> Optional parameter $domain declared before required parameter $state is implicitly treated as a required parameter workos-php/lib/SSO.php 26

### ISSUE THREAD

**Issue by BrandonNoad** [workos/workos-php#124]
https://github.com/workos/workos-php/blob/main/lib/SSO.php#L26

After upgrading to PHP v8, I'm getting the following warning:

`Severity: 8192 --> Optional parameter $domain declared before required parameter $state is implicitly treated as a required parameter workos-php/lib/SSO.php 26`

Since the first parameter, `$domain`, is optional in `getAuthorizationUrl`, but some of the parameters after it are not.

**Comment by sheldonvaughn** [comment]
Hey @BrandonNoad thanks for reporting and apologies for the inconvenience. I've gone ahead and released v1.19.0 to resolve this issue. Please let us know if we can help with anything else!

**Comment by BrandonNoad** [comment]
Thank you @sheldonvaughn 🙏

**Comment by BrandonNoad** [comment]
@sheldonvaughn what's up with the `v1.19.9` tag?

<img width="565" alt="Tags_·_workos_workos-php_🔊" src="https://user-images.githubusercontent.com/1979809/201426318-6cb017c2-dec5-4e87-a964-cb7068dce01c.png">

**Comment by sheldonvaughn** [comment]
> @sheldonvaughn what's up with the `v1.19.9` tag?
> 
> <img alt="Tags_·_workos_workos-php_🔊" width="565" src="https://user-images.githubusercontent.com/1979809/201426318-6cb017c2-dec5-4e87-a964-cb7068dce01c.png">

@BrandonNoad just a typo on my end when doing the release - sorry about that! 

I immediately added the 1.19.0 tag (which is the correct one) but let me know if the old one causes problems in any way.

**Comment by BrandonNoad** [comment]
When I updated the package with composer, my lock file is referencing `v1.19.9` now.

Not sure if that'll cause issues or not.

**Comment by sheldonvaughn** [comment]
@BrandonNoad - I see that as well! Taking a look, sorry about that!

**Comment by sheldonvaughn** [comment]
Alrighty @BrandonNoad - just dropped that version from packagist - if you `composer upgrade workos` it should downgrade to 1.19.0 - sorry for the runaround!

**Comment by BrandonNoad** [comment]
Thanks. Hopefully nobody else had installed it. Cheers.

**Comment by sheldonvaughn** [comment]
Happy to help @BrandonNoad - again my apologies for the error there. Keep us posted if anything else comes up! 

I confirmed the source code was the same for both versions (even the version number in the actual SDK said 1.19.0) so there shouldn't be any issues. They'll just see the versions go down instead of up on their next composer process which hopefully doesn't cause too much confusion 😅 . I'll add a note to release just to be safe.
