### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by Dachande663** [workos/workos-php#139]
Laravel 10 was recently released. This package (and workos-php-laravel) depends on illuminate/support, with the version curerntly capped at 9. Can the composer.json be updated to allow illuminate/support @ 10, so that it can be installed in newer Laravel installs.

**Comment by sheldonvaughn** [comment]
Hi @Dachande663 we've released v3.3.0 to allow for use with Laravel 10. Please let us know if we can help with anything further.
